# =======================================================================
# Stack       : athyper Mesh – Core Infrastructure & Observability
# Maintainer  : Atlas Digital Technology Solutions (athyper Team)
# Environment : local-dev | staging | prod
# Version     : 1.0.0
# Compose     : mesh-memorycache-config
#
# Description :
#
# =======================================================================

services:
  memorycache:
    image: redis:7.4.7-alpine
    profiles: ["mesh", "memorycache"]
    mem_limit: "${MESH_MEMORYCACHE_MEMORY_LIMIT}"
    command:
      - sh
      - -c
      - |
        redis-server /usr/local/etc/redis/redis.conf \
          --requirepass "$MESH_MEMORYCACHE_PASSWORD"
    environment:
      REDIS_PASSWORD: ${MESH_MEMORYCACHE_PASSWORD}
    volumes:
      - ${MESH_CONFIG}/memorycache/cache.conf:/usr/local/etc/redis/redis.conf:ro
      - ${MESH_DATA}/memorycache:/data
    networks: [internal]
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a \"$MESH_MEMORYCACHE_PASSWORD\" ping >/dev/null 2>&1"]
      interval: 10s
      timeout: 3s
      retries: 10
    stop_grace_period: 20s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }