# =======================================================================
# Stack       : athyper Mesh – Core Infrastructure & Observability
# Maintainer  : Atlas Digital Technology Solutions (athyper Team)
# Environment : local-dev | staging | prod
# Version     : 1.0.0
# Compose     : mesh-apps-athyper-config
#
# Description :
#
# =======================================================================

services:
  athyper-web:
    image: traefik/whoami:v1.10
    profiles: ["mesh", "gateway", "apps"]
    mem_limit: "${APPS_ATHYPER_MEMORY_LIMIT}"
    networks: [edge]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "(echo >/dev/tcp/127.0.0.1/80 >/dev/null 2>&1) || exit 1"
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    stop_grace_period: 20s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    labels:
      - traefik.enable=true
      - traefik.docker.network=athyper-mesh-edge
      - traefik.http.routers.athyper-web.entrypoints=websecure
      - traefik.http.routers.athyper-web.rule=Host(`${APPS_ATHYPER_WEB_HOST}`)
      - traefik.http.routers.athyper-web.tls.options=${MESH_TLS_OPTIONS}
      - traefik.http.routers.athyper-web.tls=true
      - traefik.http.services.athyper-web.loadbalancer.server.port=80

  athyper-api:
    image: traefik/whoami:v1.10
    profiles: ["mesh", "gateway", "apps"]
    mem_limit: "${APPS_ATHYPER_MEMORY_LIMIT}"
    networks: [edge]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "(echo >/dev/tcp/127.0.0.1/80 >/dev/null 2>&1) || exit 1"
        ]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    stop_grace_period: 20s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    labels:
      - traefik.enable=true
      - traefik.docker.network=athyper-mesh-edge
      - traefik.http.routers.athyper-api.entrypoints=websecure
      - traefik.http.routers.athyper-api.rule=Host(`${APPS_ATHYPER_API_HOST}`)
      - traefik.http.routers.athyper-api.tls.options=${MESH_TLS_OPTIONS}
      - traefik.http.routers.athyper-api.tls=true
      - traefik.http.services.athyper-api.loadbalancer.server.port=80