/* ============================================================================
   Athyper — REF Seed: Languages (ISO 639-1)
   PostgreSQL 16+

   ISO 639-1 two-letter language codes with native names and script direction.
   Depends on: 010_ref_master_tables.sql
   ============================================================================ */

insert into ref.language (code, name, native_name, iso639_2, direction, created_by)
values
  ('aa','Afar','Afaraf','aar','ltr','seed'),
  ('ab','Abkhazian','Аҧсуа','abk','ltr','seed'),
  ('af','Afrikaans','Afrikaans','afr','ltr','seed'),
  ('ak','Akan','Akan','aka','ltr','seed'),
  ('am','Amharic','አማርኛ','amh','ltr','seed'),
  ('an','Aragonese','Aragonés','arg','ltr','seed'),
  ('ar','Arabic','العربية','ara','rtl','seed'),
  ('as','Assamese','অসমীয়া','asm','ltr','seed'),
  ('av','Avaric','Авар','ava','ltr','seed'),
  ('ay','Aymara','Aymar aru','aym','ltr','seed'),
  ('az','Azerbaijani','Azərbaycan dili','aze','ltr','seed'),
  ('ba','Bashkir','Башҡорт теле','bak','ltr','seed'),
  ('be','Belarusian','Беларуская','bel','ltr','seed'),
  ('bg','Bulgarian','Български','bul','ltr','seed'),
  ('bh','Bihari languages','भोजपुरी','bih','ltr','seed'),
  ('bi','Bislama','Bislama','bis','ltr','seed'),
  ('bm','Bambara','Bamanankan','bam','ltr','seed'),
  ('bn','Bengali','বাংলা','ben','ltr','seed'),
  ('bo','Tibetan','བོད་ཡིག','bod','ltr','seed'),
  ('br','Breton','Brezhoneg','bre','ltr','seed'),
  ('bs','Bosnian','Bosanski','bos','ltr','seed'),
  ('ca','Catalan','Català','cat','ltr','seed'),
  ('ce','Chechen','Нохчийн мотт','che','ltr','seed'),
  ('ch','Chamorro','Chamoru','cha','ltr','seed'),
  ('co','Corsican','Corsu','cos','ltr','seed'),
  ('cr','Cree','ᓀᐦᐃᔭᐍᐏᐣ','cre','ltr','seed'),
  ('cs','Czech','Čeština','ces','ltr','seed'),
  ('cu','Church Slavic','Словѣньскъ','chu','ltr','seed'),
  ('cv','Chuvash','Чӑвашла','chv','ltr','seed'),
  ('cy','Welsh','Cymraeg','cym','ltr','seed'),
  ('da','Danish','Dansk','dan','ltr','seed'),
  ('de','German','Deutsch','deu','ltr','seed'),
  ('dv','Divehi','ދިވެހި','div','rtl','seed'),
  ('dz','Dzongkha','རྫོང་ཁ','dzo','ltr','seed'),
  ('ee','Ewe','Eʋegbe','ewe','ltr','seed'),
  ('el','Greek','Ελληνικά','ell','ltr','seed'),
  ('en','English','English','eng','ltr','seed'),
  ('eo','Esperanto','Esperanto','epo','ltr','seed'),
  ('es','Spanish','Español','spa','ltr','seed'),
  ('et','Estonian','Eesti','est','ltr','seed'),
  ('eu','Basque','Euskara','eus','ltr','seed'),
  ('fa','Persian','فارسی','fas','rtl','seed'),
  ('ff','Fulah','Fulfulde','ful','ltr','seed'),
  ('fi','Finnish','Suomi','fin','ltr','seed'),
  ('fj','Fijian','Vosa Vakaviti','fij','ltr','seed'),
  ('fo','Faroese','Føroyskt','fao','ltr','seed'),
  ('fr','French','Français','fra','ltr','seed'),
  ('fy','Western Frisian','Frysk','fry','ltr','seed'),
  ('ga','Irish','Gaeilge','gle','ltr','seed'),
  ('gd','Scottish Gaelic','Gàidhlig','gla','ltr','seed'),
  ('gl','Galician','Galego','glg','ltr','seed'),
  ('gn','Guarani','Avañe''ẽ','grn','ltr','seed'),
  ('gu','Gujarati','ગુજરાતી','guj','ltr','seed'),
  ('gv','Manx','Gaelg','glv','ltr','seed'),
  ('ha','Hausa','Hausa','hau','ltr','seed'),
  ('he','Hebrew','עברית','heb','rtl','seed'),
  ('hi','Hindi','हिन्दी','hin','ltr','seed'),
  ('ho','Hiri Motu','Hiri Motu','hmo','ltr','seed'),
  ('hr','Croatian','Hrvatski','hrv','ltr','seed'),
  ('ht','Haitian Creole','Kreyòl ayisyen','hat','ltr','seed'),
  ('hu','Hungarian','Magyar','hun','ltr','seed'),
  ('hy','Armenian','Հայերեն','hye','ltr','seed'),
  ('hz','Herero','Otjiherero','her','ltr','seed'),
  ('ia','Interlingua','Interlingua','ina','ltr','seed'),
  ('id','Indonesian','Bahasa Indonesia','ind','ltr','seed'),
  ('ie','Interlingue','Interlingue','ile','ltr','seed'),
  ('ig','Igbo','Igbo','ibo','ltr','seed'),
  ('ii','Sichuan Yi','ꆈꌠꉙ','iii','ltr','seed'),
  ('ik','Inupiaq','Iñupiaq','ipk','ltr','seed'),
  ('io','Ido','Ido','ido','ltr','seed'),
  ('is','Icelandic','Íslenska','isl','ltr','seed'),
  ('it','Italian','Italiano','ita','ltr','seed'),
  ('iu','Inuktitut','ᐃᓄᒃᑎᑐᑦ','iku','ltr','seed'),
  ('ja','Japanese','日本語','jpn','ltr','seed'),
  ('jv','Javanese','Basa Jawa','jav','ltr','seed'),
  ('ka','Georgian','ქართული','kat','ltr','seed'),
  ('kg','Kongo','KiKongo','kon','ltr','seed'),
  ('ki','Kikuyu','Gĩkũyũ','kik','ltr','seed'),
  ('kj','Kuanyama','Kuanyama','kua','ltr','seed'),
  ('kk','Kazakh','Қазақша','kaz','ltr','seed'),
  ('kl','Kalaallisut','Kalaallisut','kal','ltr','seed'),
  ('km','Khmer','ភាសាខ្មែរ','khm','ltr','seed'),
  ('kn','Kannada','ಕನ್ನಡ','kan','ltr','seed'),
  ('ko','Korean','한국어','kor','ltr','seed'),
  ('kr','Kanuri','Kanuri','kau','ltr','seed'),
  ('ks','Kashmiri','कश्मीरी','kas','rtl','seed'),
  ('ku','Kurdish','Kurdî','kur','rtl','seed'),
  ('kv','Komi','Коми кыв','kom','ltr','seed'),
  ('kw','Cornish','Kernewek','cor','ltr','seed'),
  ('ky','Kirghiz','Кыргызча','kir','ltr','seed'),
  ('la','Latin','Latina','lat','ltr','seed'),
  ('lb','Luxembourgish','Lëtzebuergesch','ltz','ltr','seed'),
  ('lg','Ganda','Luganda','lug','ltr','seed'),
  ('li','Limburgish','Limburgs','lim','ltr','seed'),
  ('ln','Lingala','Lingála','lin','ltr','seed'),
  ('lo','Lao','ພາສາລາວ','lao','ltr','seed'),
  ('lt','Lithuanian','Lietuvių','lit','ltr','seed'),
  ('lu','Luba-Katanga','Tshiluba','lub','ltr','seed'),
  ('lv','Latvian','Latviešu','lav','ltr','seed'),
  ('mg','Malagasy','Malagasy','mlg','ltr','seed'),
  ('mh','Marshallese','Kajin M̧ajeļ','mah','ltr','seed'),
  ('mi','Maori','Te Reo Māori','mri','ltr','seed'),
  ('mk','Macedonian','Македонски','mkd','ltr','seed'),
  ('ml','Malayalam','മലയാളം','mal','ltr','seed'),
  ('mn','Mongolian','Монгол','mon','ltr','seed'),
  ('mr','Marathi','मराठी','mar','ltr','seed'),
  ('ms','Malay','Bahasa Melayu','msa','ltr','seed'),
  ('mt','Maltese','Malti','mlt','ltr','seed'),
  ('my','Burmese','ဗမာစာ','mya','ltr','seed'),
  ('na','Nauru','Ekakairũ Naoero','nau','ltr','seed'),
  ('nb','Norwegian Bokmål','Norsk bokmål','nob','ltr','seed'),
  ('nd','North Ndebele','isiNdebele','nde','ltr','seed'),
  ('ne','Nepali','नेपाली','nep','ltr','seed'),
  ('ng','Ndonga','Owambo','ndo','ltr','seed'),
  ('nl','Dutch','Nederlands','nld','ltr','seed'),
  ('nn','Norwegian Nynorsk','Norsk nynorsk','nno','ltr','seed'),
  ('no','Norwegian','Norsk','nor','ltr','seed'),
  ('nr','South Ndebele','isiNdebele','nbl','ltr','seed'),
  ('nv','Navajo','Diné bizaad','nav','ltr','seed'),
  ('ny','Chichewa','ChiCheŵa','nya','ltr','seed'),
  ('oc','Occitan','Occitan','oci','ltr','seed'),
  ('oj','Ojibwa','ᐊᓂᔑᓈᐯᒧᐎᓐ','oji','ltr','seed'),
  ('om','Oromo','Afaan Oromoo','orm','ltr','seed'),
  ('or','Oriya','ଓଡ଼ିଆ','ori','ltr','seed'),
  ('os','Ossetian','Ирон æвзаг','oss','ltr','seed'),
  ('pa','Punjabi','ਪੰਜਾਬੀ','pan','ltr','seed'),
  ('pi','Pali','पालि','pli','ltr','seed'),
  ('pl','Polish','Polski','pol','ltr','seed'),
  ('ps','Pashto','پښتو','pus','rtl','seed'),
  ('pt','Portuguese','Português','por','ltr','seed'),
  ('qu','Quechua','Runa Simi','que','ltr','seed'),
  ('rm','Romansh','Rumantsch','roh','ltr','seed'),
  ('rn','Rundi','Ikirundi','run','ltr','seed'),
  ('ro','Romanian','Română','ron','ltr','seed'),
  ('ru','Russian','Русский','rus','ltr','seed'),
  ('rw','Kinyarwanda','Ikinyarwanda','kin','ltr','seed'),
  ('sa','Sanskrit','संस्कृतम्','san','ltr','seed'),
  ('sc','Sardinian','Sardu','srd','ltr','seed'),
  ('sd','Sindhi','سنڌي','snd','rtl','seed'),
  ('se','Northern Sami','Davvisámegiella','sme','ltr','seed'),
  ('sg','Sango','Yângâ tî sängö','sag','ltr','seed'),
  ('si','Sinhala','සිංහල','sin','ltr','seed'),
  ('sk','Slovak','Slovenčina','slk','ltr','seed'),
  ('sl','Slovenian','Slovenščina','slv','ltr','seed'),
  ('sm','Samoan','Gagana Samoa','smo','ltr','seed'),
  ('sn','Shona','chiShona','sna','ltr','seed'),
  ('so','Somali','Soomaali','som','ltr','seed'),
  ('sq','Albanian','Shqip','sqi','ltr','seed'),
  ('sr','Serbian','Српски','srp','ltr','seed'),
  ('ss','Swati','SiSwati','ssw','ltr','seed'),
  ('st','Southern Sotho','Sesotho','sot','ltr','seed'),
  ('su','Sundanese','Basa Sunda','sun','ltr','seed'),
  ('sv','Swedish','Svenska','swe','ltr','seed'),
  ('sw','Swahili','Kiswahili','swa','ltr','seed'),
  ('ta','Tamil','தமிழ்','tam','ltr','seed'),
  ('te','Telugu','తెలుగు','tel','ltr','seed'),
  ('tg','Tajik','Тоҷикӣ','tgk','ltr','seed'),
  ('th','Thai','ไทย','tha','ltr','seed'),
  ('ti','Tigrinya','ትግርኛ','tir','ltr','seed'),
  ('tk','Turkmen','Türkmen','tuk','ltr','seed'),
  ('tl','Tagalog','Wikang Tagalog','tgl','ltr','seed'),
  ('tn','Tswana','Setswana','tsn','ltr','seed'),
  ('to','Tonga','Faka Tonga','ton','ltr','seed'),
  ('tr','Turkish','Türkçe','tur','ltr','seed'),
  ('ts','Tsonga','Xitsonga','tso','ltr','seed'),
  ('tt','Tatar','Татарча','tat','ltr','seed'),
  ('tw','Twi','Twi','twi','ltr','seed'),
  ('ty','Tahitian','Reo Tahiti','tah','ltr','seed'),
  ('ug','Uyghur','ئۇيغۇرچە','uig','rtl','seed'),
  ('uk','Ukrainian','Українська','ukr','ltr','seed'),
  ('ur','Urdu','اردو','urd','rtl','seed'),
  ('uz','Uzbek','O''zbek','uzb','ltr','seed'),
  ('ve','Venda','Tshivenḓa','ven','ltr','seed'),
  ('vi','Vietnamese','Tiếng Việt','vie','ltr','seed'),
  ('vo','Volapük','Volapük','vol','ltr','seed'),
  ('wa','Walloon','Walon','wln','ltr','seed'),
  ('wo','Wolof','Wollof','wol','ltr','seed'),
  ('xh','Xhosa','isiXhosa','xho','ltr','seed'),
  ('yi','Yiddish','ייִדיש','yid','rtl','seed'),
  ('yo','Yoruba','Yorùbá','yor','ltr','seed'),
  ('za','Zhuang','Saɯ cueŋƅ','zha','ltr','seed'),
  ('zh','Chinese','中文','zho','ltr','seed'),
  ('zu','Zulu','isiZulu','zul','ltr','seed')
on conflict (code) do nothing;
