/* ============================================================================
   Athyper — REF Seed: Commodity Classifications
   PostgreSQL 16+

   Domains: UNSPSC (segments) + HS (chapters)
   Depends on: 010_ref_master_tables.sql
   ============================================================================ */

-- ============================================================================
-- Domains
-- ============================================================================
insert into ref.commodity_domain (code, name, standard, version, created_by)
values
  ('unspsc', 'United Nations Standard Products and Services Code', 'UNSPSC', 'v26', 'seed'),
  ('hs',     'Harmonized Commodity Description and Coding System', 'HS',     '2022', 'seed')
on conflict (code) do nothing;

-- ============================================================================
-- UNSPSC Segments (Level 1 — 2-digit)
-- ============================================================================
insert into ref.commodity_code (domain_code, code, name, description, level_no, created_by)
values
  ('unspsc','10','Live Plant and Animal Material','Live animals, plants, and raw biological materials',1,'seed'),
  ('unspsc','11','Mineral and Textile and Inedible Plant and Animal Materials','Raw mineral, textile, and inedible biological materials',1,'seed'),
  ('unspsc','12','Chemicals including Bio Chemicals and Gas Materials','Chemical substances, biochemicals, and gas materials',1,'seed'),
  ('unspsc','13','Resin and Rosin and Rubber and Foam and Film and Elastomeric Materials','Polymeric and elastomeric materials',1,'seed'),
  ('unspsc','14','Paper Materials and Products','Paper, paperboard, and related products',1,'seed'),
  ('unspsc','15','Fuels and Fuel Additives and Lubricants','Petroleum fuels, additives, lubricants, and greases',1,'seed'),
  ('unspsc','20','Mining and Well Drilling Machinery and Accessories','Mining, drilling, and extraction equipment',1,'seed'),
  ('unspsc','21','Farming and Fishing and Forestry and Wildlife Machinery','Agricultural, fishing, and forestry equipment',1,'seed'),
  ('unspsc','22','Building and Construction Machinery and Accessories','Construction and earthmoving equipment',1,'seed'),
  ('unspsc','23','Industrial Manufacturing and Processing Machinery','Manufacturing and processing equipment',1,'seed'),
  ('unspsc','24','Material Handling and Conditioning and Storage Machinery','Material handling, storage, and packaging equipment',1,'seed'),
  ('unspsc','25','Commercial and Military and Private Vehicles and their Accessories','Vehicles and vehicle accessories',1,'seed'),
  ('unspsc','26','Power Generation and Distribution Machinery and Accessories','Power generation, transmission, and distribution',1,'seed'),
  ('unspsc','27','Tools and General Machinery','Hand tools, power tools, and general machinery',1,'seed'),
  ('unspsc','30','Structures and Building and Construction and Manufacturing Components','Prefabricated structures and building components',1,'seed'),
  ('unspsc','31','Manufacturing Components and Supplies','Components, fittings, and manufacturing supplies',1,'seed'),
  ('unspsc','32','Electronic Components and Supplies','Electronic components, semiconductors, and accessories',1,'seed'),
  ('unspsc','39','Lighting Fixtures and Accessories and Supplies','Lamps, lighting fixtures, and electrical accessories',1,'seed'),
  ('unspsc','40','Distribution and Conditioning Systems and Equipment','HVAC, plumbing, and fluid distribution',1,'seed'),
  ('unspsc','41','Laboratory and Measuring and Observing and Testing Equipment','Lab instruments, measurement, and testing devices',1,'seed'),
  ('unspsc','42','Medical Equipment and Accessories and Supplies','Medical devices, hospital equipment, and supplies',1,'seed'),
  ('unspsc','43','Information Technology Broadcasting and Telecommunications','IT hardware, software, telecom, and broadcasting',1,'seed'),
  ('unspsc','44','Office Equipment and Accessories and Supplies','Office machines, furniture accessories, and supplies',1,'seed'),
  ('unspsc','45','Printing and Photographic and Audio and Visual Equipment','Printing, imaging, AV, and photographic equipment',1,'seed'),
  ('unspsc','46','Defense and Law Enforcement and Security and Safety Equipment','Defense, security, fire safety, and law enforcement',1,'seed'),
  ('unspsc','47','Cleaning Equipment and Supplies','Janitorial, cleaning, and sanitation products',1,'seed'),
  ('unspsc','48','Service Industry Machinery and Equipment and Supplies','Hospitality, food service, and vending equipment',1,'seed'),
  ('unspsc','49','Sports and Recreational Equipment and Supplies and Accessories','Sports, recreation, fitness, and outdoor equipment',1,'seed'),
  ('unspsc','50','Food Beverage and Tobacco Products','Food, beverages, and tobacco',1,'seed'),
  ('unspsc','51','Drugs and Pharmaceutical Products','Pharmaceuticals, biologics, and drug products',1,'seed'),
  ('unspsc','52','Domestic Appliances and Supplies and Consumer Electronic Products','Home appliances and consumer electronics',1,'seed'),
  ('unspsc','53','Apparel and Luggage and Personal Care Products','Clothing, luggage, footwear, and personal care',1,'seed'),
  ('unspsc','54','Timepieces and Jewelry and Gemstone Products','Watches, clocks, jewelry, and precious stones',1,'seed'),
  ('unspsc','55','Published Products','Books, periodicals, maps, and published materials',1,'seed'),
  ('unspsc','56','Furniture and Furnishings','Furniture, fixtures, and interior furnishings',1,'seed'),
  ('unspsc','60','Musical Instruments and Games and Toys and Arts and Crafts','Musical instruments, games, toys, and craft supplies',1,'seed'),
  ('unspsc','70','Farming and Fishing and Forestry and Wildlife Contracting Services','Agricultural and natural resource services',1,'seed'),
  ('unspsc','71','Mining and Oil and Gas Services','Mining, drilling, and extraction services',1,'seed'),
  ('unspsc','72','Building and Facility Construction and Maintenance Services','Construction, renovation, and facility maintenance',1,'seed'),
  ('unspsc','73','Industrial Production and Manufacturing Services','Contract manufacturing and industrial services',1,'seed'),
  ('unspsc','76','Industrial Cleaning Services','Specialized industrial cleaning services',1,'seed'),
  ('unspsc','77','Environmental Services','Environmental management and remediation',1,'seed'),
  ('unspsc','78','Transportation and Storage and Mail Services','Freight, logistics, postal, and storage services',1,'seed'),
  ('unspsc','80','Management and Business Professionals and Administrative Services','Management consulting and business services',1,'seed'),
  ('unspsc','81','Engineering and Research and Technology Based Services','Engineering, R&D, and technology services',1,'seed'),
  ('unspsc','82','Editorial and Design and Graphic and Fine Art Services','Creative, design, and media production services',1,'seed'),
  ('unspsc','83','Public Utilities and Public Sector Related Services','Utility and public infrastructure services',1,'seed'),
  ('unspsc','84','Financial and Insurance Services','Banking, insurance, and financial services',1,'seed'),
  ('unspsc','85','Healthcare Services','Medical, dental, and health-related services',1,'seed'),
  ('unspsc','86','Education and Training Services','Education, training, and e-learning services',1,'seed'),
  ('unspsc','90','Travel and Food and Lodging and Entertainment Services','Travel, hospitality, and entertainment services',1,'seed'),
  ('unspsc','91','Personal and Domestic Services','Personal care, household, and domestic services',1,'seed'),
  ('unspsc','92','National Defense and Public Order and Security and Safety Services','Defense, public safety, and emergency services',1,'seed'),
  ('unspsc','93','Politics and Civic Affairs Services','Government, political, and civic services',1,'seed'),
  ('unspsc','94','Organizations and Clubs','Membership organizations, clubs, and associations',1,'seed'),
  ('unspsc','95','Land and Buildings and Structures and Thoroughfares','Real property, buildings, and infrastructure',1,'seed')
on conflict (domain_code, code) do nothing;

-- ============================================================================
-- HS Chapters (Level 1 — 2-digit)
-- ============================================================================
insert into ref.commodity_code (domain_code, code, name, description, level_no, created_by)
values
  ('hs','01','Live Animals','Live animals',1,'seed'),
  ('hs','02','Meat and Edible Meat Offal','Meat and edible meat offal',1,'seed'),
  ('hs','03','Fish and Crustaceans','Fish, crustaceans, molluscs and other aquatic invertebrates',1,'seed'),
  ('hs','04','Dairy Produce','Dairy produce; birds'' eggs; natural honey',1,'seed'),
  ('hs','05','Products of Animal Origin','Products of animal origin, not elsewhere specified',1,'seed'),
  ('hs','06','Live Trees and Other Plants','Live trees and other plants; bulbs, roots; cut flowers',1,'seed'),
  ('hs','07','Edible Vegetables','Edible vegetables and certain roots and tubers',1,'seed'),
  ('hs','08','Edible Fruit and Nuts','Edible fruit and nuts; peel of citrus fruit or melons',1,'seed'),
  ('hs','09','Coffee, Tea, Spices','Coffee, tea, maté and spices',1,'seed'),
  ('hs','10','Cereals','Cereals',1,'seed'),
  ('hs','11','Products of the Milling Industry','Products of the milling industry; malt; starches',1,'seed'),
  ('hs','12','Oil Seeds and Oleaginous Fruits','Oil seeds and oleaginous fruits; miscellaneous grains',1,'seed'),
  ('hs','13','Lac, Gums, Resins','Lac; gums, resins and other vegetable saps and extracts',1,'seed'),
  ('hs','14','Vegetable Plaiting Materials','Vegetable plaiting materials; vegetable products',1,'seed'),
  ('hs','15','Animal or Vegetable Fats and Oils','Animal or vegetable fats and oils',1,'seed'),
  ('hs','16','Preparations of Meat or Fish','Preparations of meat, of fish or of crustaceans',1,'seed'),
  ('hs','17','Sugars and Sugar Confectionery','Sugars and sugar confectionery',1,'seed'),
  ('hs','18','Cocoa and Cocoa Preparations','Cocoa and cocoa preparations',1,'seed'),
  ('hs','19','Preparations of Cereals','Preparations of cereals, flour, starch or milk',1,'seed'),
  ('hs','20','Preparations of Vegetables or Fruit','Preparations of vegetables, fruit, nuts',1,'seed'),
  ('hs','21','Miscellaneous Edible Preparations','Miscellaneous edible preparations',1,'seed'),
  ('hs','22','Beverages, Spirits and Vinegar','Beverages, spirits and vinegar',1,'seed'),
  ('hs','23','Residues and Waste from Food','Residues and waste from food industries; prepared animal feed',1,'seed'),
  ('hs','24','Tobacco and Manufactured Tobacco','Tobacco and manufactured tobacco substitutes',1,'seed'),
  ('hs','25','Salt, Sulphur, Earths and Stone','Salt; sulphur; earths and stone; lime and cement',1,'seed'),
  ('hs','26','Ores, Slag and Ash','Ores, slag and ash',1,'seed'),
  ('hs','27','Mineral Fuels and Oils','Mineral fuels, mineral oils and products of their distillation',1,'seed'),
  ('hs','28','Inorganic Chemicals','Inorganic chemicals; compounds of precious metals',1,'seed'),
  ('hs','29','Organic Chemicals','Organic chemicals',1,'seed'),
  ('hs','30','Pharmaceutical Products','Pharmaceutical products',1,'seed'),
  ('hs','31','Fertilisers','Fertilisers',1,'seed'),
  ('hs','32','Tanning or Dyeing Extracts','Tanning or dyeing extracts; dyes, pigments, paints',1,'seed'),
  ('hs','33','Essential Oils and Cosmetics','Essential oils and resinoids; perfumery, cosmetic preparations',1,'seed'),
  ('hs','34','Soap, Waxes, Polishing','Soap, organic surface-active agents; waxes; candles',1,'seed'),
  ('hs','35','Albuminoidal Substances','Albuminoidal substances; modified starches; glues; enzymes',1,'seed'),
  ('hs','36','Explosives and Pyrotechnics','Explosives; pyrotechnic products; matches',1,'seed'),
  ('hs','37','Photographic and Cinematographic','Photographic or cinematographic goods',1,'seed'),
  ('hs','38','Miscellaneous Chemical Products','Miscellaneous chemical products',1,'seed'),
  ('hs','39','Plastics and Articles Thereof','Plastics and articles thereof',1,'seed'),
  ('hs','40','Rubber and Articles Thereof','Rubber and articles thereof',1,'seed'),
  ('hs','41','Raw Hides and Skins','Raw hides and skins (other than furskins) and leather',1,'seed'),
  ('hs','42','Articles of Leather','Articles of leather; saddlery and harness; travel goods',1,'seed'),
  ('hs','43','Furskins and Artificial Fur','Furskins and artificial fur; manufactures thereof',1,'seed'),
  ('hs','44','Wood and Articles of Wood','Wood and articles of wood; wood charcoal',1,'seed'),
  ('hs','45','Cork and Articles of Cork','Cork and articles of cork',1,'seed'),
  ('hs','46','Manufactures of Straw','Manufactures of straw, of esparto or other plaiting materials',1,'seed'),
  ('hs','47','Wood Pulp','Pulp of wood or of other fibrous cellulosic material',1,'seed'),
  ('hs','48','Paper and Paperboard','Paper and paperboard; articles of paper pulp',1,'seed'),
  ('hs','49','Printed Books and Newspapers','Printed books, newspapers, pictures; manuscripts',1,'seed'),
  ('hs','50','Silk','Silk',1,'seed'),
  ('hs','51','Wool and Animal Hair','Wool, fine or coarse animal hair; horsehair yarn',1,'seed'),
  ('hs','52','Cotton','Cotton',1,'seed'),
  ('hs','53','Other Vegetable Textile Fibres','Other vegetable textile fibres; paper yarn',1,'seed'),
  ('hs','54','Man-made Filaments','Man-made filaments; strip of man-made textile materials',1,'seed'),
  ('hs','55','Man-made Staple Fibres','Man-made staple fibres',1,'seed'),
  ('hs','56','Wadding, Felt and Nonwovens','Wadding, felt and nonwovens; special yarns; twine',1,'seed'),
  ('hs','57','Carpets and Other Floor Coverings','Carpets and other textile floor coverings',1,'seed'),
  ('hs','58','Special Woven Fabrics','Special woven fabrics; tufted textile fabrics; lace',1,'seed'),
  ('hs','59','Impregnated Textile Fabrics','Impregnated, coated, covered or laminated textile fabrics',1,'seed'),
  ('hs','60','Knitted or Crocheted Fabrics','Knitted or crocheted fabrics',1,'seed'),
  ('hs','61','Articles of Apparel, Knitted','Articles of apparel and clothing accessories, knitted',1,'seed'),
  ('hs','62','Articles of Apparel, Not Knitted','Articles of apparel and clothing accessories, not knitted',1,'seed'),
  ('hs','63','Other Made Up Textile Articles','Other made up textile articles; worn clothing',1,'seed'),
  ('hs','64','Footwear','Footwear, gaiters and the like',1,'seed'),
  ('hs','65','Headgear','Headgear and parts thereof',1,'seed'),
  ('hs','66','Umbrellas and Walking Sticks','Umbrellas, sun umbrellas, walking-sticks',1,'seed'),
  ('hs','67','Prepared Feathers','Prepared feathers; artificial flowers; articles of human hair',1,'seed'),
  ('hs','68','Articles of Stone and Cement','Articles of stone, plaster, cement, asbestos, mica',1,'seed'),
  ('hs','69','Ceramic Products','Ceramic products',1,'seed'),
  ('hs','70','Glass and Glassware','Glass and glassware',1,'seed'),
  ('hs','71','Precious Metals and Stones','Natural or cultured pearls, precious or semi-precious stones',1,'seed'),
  ('hs','72','Iron and Steel','Iron and steel',1,'seed'),
  ('hs','73','Articles of Iron or Steel','Articles of iron or steel',1,'seed'),
  ('hs','74','Copper and Articles Thereof','Copper and articles thereof',1,'seed'),
  ('hs','75','Nickel and Articles Thereof','Nickel and articles thereof',1,'seed'),
  ('hs','76','Aluminium and Articles Thereof','Aluminium and articles thereof',1,'seed'),
  ('hs','78','Lead and Articles Thereof','Lead and articles thereof',1,'seed'),
  ('hs','79','Zinc and Articles Thereof','Zinc and articles thereof',1,'seed'),
  ('hs','80','Tin and Articles Thereof','Tin and articles thereof',1,'seed'),
  ('hs','81','Other Base Metals','Other base metals; cermets; articles thereof',1,'seed'),
  ('hs','82','Tools and Cutlery','Tools, implements, cutlery, spoons and forks of base metal',1,'seed'),
  ('hs','83','Miscellaneous Articles of Base Metal','Miscellaneous articles of base metal',1,'seed'),
  ('hs','84','Nuclear Reactors, Boilers, Machinery','Nuclear reactors, boilers, machinery and mechanical appliances',1,'seed'),
  ('hs','85','Electrical Machinery and Equipment','Electrical machinery and equipment; sound recorders',1,'seed'),
  ('hs','86','Railway or Tramway Equipment','Railway or tramway locomotives, rolling-stock',1,'seed'),
  ('hs','87','Vehicles Other Than Railway','Vehicles other than railway or tramway rolling-stock',1,'seed'),
  ('hs','88','Aircraft and Spacecraft','Aircraft, spacecraft, and parts thereof',1,'seed'),
  ('hs','89','Ships, Boats and Floating Structures','Ships, boats and floating structures',1,'seed'),
  ('hs','90','Optical and Medical Instruments','Optical, photographic, medical or surgical instruments',1,'seed'),
  ('hs','91','Clocks and Watches','Clocks and watches and parts thereof',1,'seed'),
  ('hs','92','Musical Instruments','Musical instruments; parts and accessories of such articles',1,'seed'),
  ('hs','93','Arms and Ammunition','Arms and ammunition; parts and accessories thereof',1,'seed'),
  ('hs','94','Furniture and Bedding','Furniture; bedding, mattresses; lamps; prefabricated buildings',1,'seed'),
  ('hs','95','Toys, Games and Sports Equipment','Toys, games and sports requisites; parts and accessories',1,'seed'),
  ('hs','96','Miscellaneous Manufactured Articles','Miscellaneous manufactured articles',1,'seed'),
  ('hs','97','Works of Art','Works of art, collectors'' pieces and antiques',1,'seed')
on conflict (domain_code, code) do nothing;
