# =======================================================================
# Stack       : athyper Mesh – Core Infrastructure & Observability
# Maintainer  : Atlas Digital Technology Solutions (athyper Team)
# Environment : local-dev | staging | prod
# Version     : 1.0.0
# Compose     : mesh-iam-config
#
# Description :
#
# =======================================================================

services:
  iam:
    image: quay.io/keycloak/keycloak:26.5.1
    profiles: ["mesh", "iam"]
    mem_limit: "${MESH_IAM_MEMORY_LIMIT}"
    command: ["start-dev"]
    environment:
      KEYCLOAK_ADMIN: ${MESH_IAM_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${MESH_IAM_ADMIN_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HTTP_ENABLED: "true"
      KC_HOSTNAME: ${MESH_IAM_HOST}
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "true"
      KC_DB: postgres
      KC_DB_URL: ${MESH_IAM_DB_URL}
      KC_DB_USERNAME: ${MESH_IAM_DB_USERNAME}
      KC_DB_PASSWORD: ${MESH_IAM_DB_PASSWORD}
      KC_DB_POOL_INITIAL_SIZE: 5
      KC_DB_POOL_MAX_SIZE: 20
    networks: [edge]
    depends_on:
      gateway:
        condition: service_healthy
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "(echo >/dev/tcp/127.0.0.1/8080 >/dev/null 2>&1) \
          && (wget -q --spider http://127.0.0.1:8080/health/ready 2>/dev/null || true) \
          || exit 1"
        ]
      interval: 10s
      timeout: 3s
      retries: 20
      start_period: 20s
    stop_grace_period: 10s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    labels:
      - traefik.enable=true
      - traefik.docker.network=athyper-mesh-edge
      - traefik.http.routers.iam.entrypoints=websecure
      - traefik.http.routers.iam.priority=10
      - traefik.http.routers.iam.rule=Host(`${MESH_IAM_HOST}`)
      - traefik.http.routers.iam.tls.options=${MESH_TLS_OPTIONS}
      - traefik.http.routers.iam.tls=true
      - traefik.http.services.iam.loadbalancer.server.port=8080