# =======================================================================
# Stack       : athyper Mesh – Core Infrastructure & Observability
# Maintainer  : Atlas Digital Technology Solutions (athyper Team)
# Environment : local | staging | production
# Version     : 1.0.0
# Compose     : mesh-tracing-config
#
# Description :
#
# =======================================================================

services:
  tracing:
    image: grafana/tempo:2.9.0
    profiles: ["mesh", "telemetry"]
    mem_limit: "${TRACING_MEMORY_LIMIT}"
    command: ["-config.file=/etc/tempo.yml"]
    volumes:
      - ${MESH_CONFIG}/telemetry/tracing/config.yml:/etc/tempo.yml:ro
      - ${MESH_DATA}/telemetry/tracing:/var/tempo
    networks: [edge, internal]
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3200/ready"]
      interval: 10s
      timeout: 3s
      retries: 10
    stop_grace_period: 20s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    labels:
      - traefik.docker.network=athyper-mesh-edge
      - traefik.enable=true
      - traefik.http.routers.tracing.entrypoints=websecure
      - traefik.http.routers.tracing.middlewares=${DASHBOARD_AUTH_MW}
      - traefik.http.routers.tracing.rule=Host(`${TRACES_HOST}`)
      - traefik.http.routers.tracing.tls.options=${GATEWAY_TLS_OPTIONS}
      - traefik.http.routers.tracing.tls=true
      - traefik.http.services.tracing.loadbalancer.server.port=3200
