# =======================================================================
# Stack       : athyper Mesh – Core Infrastructure & Observability
# Maintainer  : Atlas Digital Technology Solutions (athyper Team)
# Environment : local-dev | staging | prod
# Version     : 1.0.0
# Compose     : mesh-telemetry-config
#
# Description :
#
# =======================================================================

services:
  telemetry:
    image: grafana/grafana:12.3.1
    profiles: ["mesh", "telemetry"]
    mem_limit: "${MESH_TELEMETRY_MEMORY_LIMIT}"
    environment:
      GF_SECURITY_ADMIN_USER: ${MESH_TELEMETRY_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${MESH_TELEMETRY_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ${MESH_CONFIG}/telemetry/provisioning:/etc/grafana/provisioning:ro
      - ${MESH_DATA}/telemetry/observability:/var/lib/grafana
    networks: [edge, internal]
    depends_on:
      gateway:
        condition: service_healthy
      metrics:
        condition: service_started
      logging:
        condition: service_started
      tracing:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 3s
      retries: 10
    stop_grace_period: 20s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    init: true
    logging:
      driver: json-file
      options: { max-size: "10m", max-file: "3" }
    labels:
      - traefik.docker.network=athyper-mesh-edge
      - traefik.enable=true
      - traefik.http.routers.telemetry.entrypoints=websecure
      - traefik.http.routers.telemetry.middlewares=${MESH_DASHBOARD_AUTH_MW}
      - traefik.http.routers.telemetry.rule=Host(`${MESH_TELEMETRY_HOST}`)
      - traefik.http.routers.telemetry.tls.options=${MESH_TLS_OPTIONS}
      - traefik.http.routers.telemetry.tls=true
      - traefik.http.services.telemetry.loadbalancer.server.port=3000